<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Soal;

class SoalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = array(
            array(
                'nama_soal' => 'Matematika Dasar (X)',
                'butir_soal' => 25,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Agama dan Budi Pekerti (X)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Pancasila dan Kewarganegaraan (X)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Indonesia (X)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Inggris (X)',
                'butir_soal' => 50,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Seni Budaya (X)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Jasmani dan Rohani (X)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Jaringan Dasar (X)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => 6,
                'tipe_soal'     => 'Produktif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Robotic Dasar Dasar (X)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'X',
                'jurusan_id'    => 7,
                'tipe_soal'     => 'Produktif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),


            array(
                'nama_soal' => 'Matematika Menengah (XI)',
                'butir_soal' => 25,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Agama dan Budi Pekerti (XI)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Pancasila dan Kewarganegaraan (XI)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Indonesia (XI)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Inggris (XI)',
                'butir_soal' => 50,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Seni Budaya (XI)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Jasmani dan Rohani (XI)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XI',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),

            array(
                'nama_soal' => 'Matematika Dasar (XII)',
                'butir_soal' => 25,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Agama dan Budi Pekerti (XII)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Pancasila dan Kewarganegaraan (XII)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Indonesia (XII)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Bahasa Inggris (XII)',
                'butir_soal' => 50,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Seni Budaya (XII)',
                'butir_soal' => 50,
                'acak' => false,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
            array(
                'nama_soal' => 'Pendidikan Jasmani dan Rohani (XII)',
                'butir_soal' => 60,
                'acak' => true,
                'waktu_mulai' => '2023-04-20 07:30:00',
                'durasi'    => '01:30:00',
                'tingkat_ref' => 'XII',
                'jurusan_id'    => null,
                'tipe_soal'     => 'Normatif Adaptif',
                'created_at'    => date("Y-m-d H:i:s"),
                'updated_at'    => date("Y-m-d H:i:s"),
            ),
        );

        Soal::insert($data);
    }
}
