version: '3.8'

services:

    # PHP-FPM - Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8081:8000
        container_name: ujian-laravel-app
        working_dir: /var/www
        # command: php artisan octane:start --host=0.0.0.0
        command: rr serve -c .rr.yaml
        volumes:
            - ./:/var/www
            
        networks:
            - simulasi-laravel-network

    # Nginx - Service
    # webserver:
    #     image: nginx:latest
    #     container_name: ujian-laravel-webserver

    #     ports:
    #         - 8081:90

    #     volumes:
    #         - ./:/var/www
    #         - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    #     networks:
    #         - simulasi-laravel-network

    # Nginx-RR (Error) - Service
    # webserver:
    #     image: nginx:stable-alpine
    #     container_name: ujian-laravel-webserver

    #     ports:
    #         - 8000:80

    #     volumes:
            
    #         - ./docker/rr-nginx/rr.conf:/etc/nginx/conf.d/default.conf

    #     networks:
    #         - simulasi-laravel-network

    # MariaDB - Service
    db:
        image: mariadb:10.7.8
        container_name: ujian-laravel-db

        ports:
            - 3307:3306

        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}

        volumes:
            - mariadbdata:/var/lib/mysql

        networks:
            - simulasi-laravel-network

    phpmyadmin:
        image: phpmyadmin:latest
        container_name: ujian-laravel-pma
        depends_on:
            - db
        environment:
            PMA_HOST: db
        ports:
            - 8082:80
        networks:
            - simulasi-laravel-network

# Volumes
volumes:
    mariadbdata:
        driver: local

# Networks
networks:
    simulasi-laravel-network:
        driver: bridge
